# Generated by Django 4.1.2 on 2022-10-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_service_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='cust_name',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
